---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        env:
        - name: REDMINE_DB_POSTGRES
          value: database
        - name: REDMINE_DB_USERNAME
          value: testuser
        - name: REDMINE_DB_PASSWORD
          valueFrom:
           secretKeyRef:
            name: my-secret
            key: db-pass  
        - name: REDMINE_DB_DATABASE
          value: testdatabase
        - name: REDMINE_SECRET_KEY_BASE
          valueFrom:
           secretKeyRef:
            name: supersecretkey
            key: redmine
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 300Mi
