--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
spec:
  replicas: 1
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0        
  selector:
    matchLabels:
      app: fac
  template:
    metadata:
      labels:
        app: fac
    spec:
      containers:
      - image: factoriotools/factorio:0.18.34
        name: factorio
        ports:
        - containerPort: 34197
          protocol: UDP
        - containerPort: 27015
          protocol: TCP
